### PR TITLE
Refactor random init

### PR DESCRIPTION
**Pull request by kfriedrichs**
Random initialization was refactored:
* `area_block` and `area_target` are renamed to `obj_area` and `target_area`
* only one parameter is used for target creation instead of two: if no targets are wanted, set `target_area` to None / null, otherwise specify the area as before (e.g., "bottom")

### CODE REVIEW

**Comment by kfriedrichs** [comment]
I should note this was branched from the targets_on_bg_layer branch so we better pass PR #32 before 😅

**Comment by kfriedrichs** [comment]
Oh I am only now looking closer at the #34 PR. It might be the easiest to re-apply the changes here once the other two PRs are through.

**Comment by phisad** [comment]
> Oh I am only now looking closer at the #34 PR. It might be the easiest to re-apply the changes here once the other two PRs are through.

OK, then we keep this on hold for now.

**Comment by kfriedrichs** [comment]
Closing this now, changes were re-applied in PR #40.

**Pull request closed without merging**
